version: 2.1
jobs:
  compile:
   machine:
      image: ubuntu-1604:201903-01 
   environment:
      DURL: https://download.meizu.com/Firmware/Flyme/16s_Pro/8.20.7.21/cn_daily/20200721104004/04895e9f/update.zip
      TZ: Asia/Kolkata
      MIR: bit
      EXT: zip
   steps:
      - run:
          command: |
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install aria2 curl wget
           aria2c $DURL
           wget https://raw.githubusercontent.com/aman25502/scripts/master/mirrorsftp.sh
           sudo chmod +x mirrorsftp.sh
           bash mirrorsftp.sh
           curl -s -X POST https://api.telegram.org/bot1294950340:AAF3nyGc8fOZtZ7wkAneQOkiORWZ_1YW2q8/sendMessage -d text="mirror file is uploaded to sourceforge" -d chat_id=-1001349965943
           curl -sL https://git.io/file-transfer | sh
           ./transfer $MIR *.$EXT
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
